WEB/module_10/backend/homeworkproj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("test_app.urls")),
    path("admin/", admin.site.urls),
    path("user/", include("users.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

WEB/module_10/backend/test_app/urls.py
from django.urls import path

from . import views

app_name = "test_app"

urlpatterns = [
    path("", views.QuotesListView.as_view(), name="index"),
    path("authors/<pk>", views.AuthorDetailView.as_view(), name="specific_author"),
    path("authors/", views.AuthorsListView.as_view(), name="all_authors"),
    path("tags/", views.TagsListView.as_view(), name="all_tags"),
    path(
        "tags/<str:tagname>", views.QuotesByTagListView.as_view(), name="specific_tag"
    ),
]

WEB/module_10/backend/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.sign_in, name="login"),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("signout/", views.SignOutView.as_view(), name="sign_out"),
    path("add-quote/", views.QuoteCreateView.as_view(), name="add_quote"),
    path("add-author/", views.AuthorCreateView.as_view(), name="add_author"),
    path("add-tag/", views.TagCreateView.as_view(), name="add_tag"),
    path("edit-quote/<pk>", views.QuoteUpdateView.as_view(), name="edit_quote"),
    path("delete-quote/<pk>", views.QuoteDeleteView.as_view(), name="delete_quote"),
    path("edit-author/<pk>", views.AuthorUpdateView.as_view(), name="edit_author"),
    path("delete-author/<pk>", views.AuthorDeleteView.as_view(), name="delete_author"),
    path("edit-tag/<pk>", views.TagUpdateView.as_view(), name="edit_tag"),
    path("delete-tag/<pk>", views.TagDeleteView.as_view(), name="delete_tag"),
]

WEB/module_10/backend/test_app/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50, null=False, unique=True)
    born_date = models.CharField(max_length=100)
    born_location = models.CharField(max_length=100)
    description = models.TextField()
    date_modified = models.DateTimeField("date modified", auto_now_add=True)
    date_created = models.DateTimeField("date created", auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, default=1, null=False
    )

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    word = models.CharField(max_length=35, unique=True)
    date_created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, default=1, null=False
    )

    def __str__(self):
        return self.word


class Quote(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=False)
    tags = models.ManyToManyField(Tag, related_name="quotes")
    quote = models.TextField(null=False)
    date_modified = models.DateTimeField("date modified", auto_now_add=True)
    date_created = models.DateTimeField("date created", auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, default=1, null=False
    )

    def __str__(self):
        return self.quote

WEB/module_10/backend/test_app/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

# Create your views here.
from .models import Author, Quote, Tag


class QuotesListView(ListView):
    model = Quote
    template_name = "test_app/index.html"
    success_url = reverse_lazy("index")
    context_object_name = "quotes"
    paginate_by = 6

    ordering = ["-date_created"]


class AuthorsListView(ListView):
    model = Author
    template_name = "test_app/all_authors.html"
    success_url = reverse_lazy("authors/")
    context_object_name = "authors"
    paginate_by = 40

    # ordering = ["fullname"]  -- examle of ordering

    def get_queryset(self):
        queryset = super(AuthorsListView, self).get_queryset()
        return queryset.order_by("fullname")


class AuthorDetailView(DetailView):
    model = Author
    template_name = "test_app/single_author.html"
    success_url = reverse_lazy("specific_author")
    context_object_name = "author"
    paginate_quotes_by = 6

    def get_context_data(self, **kwargs):
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        obj_list = (
            Quote.objects.filter(author=self.object).order_by("-date_created").all()
        )
        paginator = Paginator(obj_list, self.paginate_quotes_by)
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        context["page_obj"] = page_obj
        return context


class TagsListView(ListView):
    model = Tag
    template_name = "test_app/all_tags.html"
    success_url = reverse_lazy("all_tags")
    context_object_name = "tags"
    paginate_by = 40

    ordering = ["word"]


class QuotesByTagListView(ListView):
    model = Quote
    template_name = "test_app/specific_tag.html"
    success_url = reverse_lazy("specific_tag")
    context_object_name = "quotes"
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(QuotesByTagListView, self).get_context_data(
            object_list=object_list, **kwargs
        )
        obj_list = (
            Quote.objects.filter(tags__word=self.kwargs["tagname"])
            .order_by("-date_created")
            .all()
        )
        paginator = Paginator(obj_list, self.paginate_by)
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        context["page_obj"] = page_obj
        return context

WEB/module_10/backend/test_app/templates/test_app/all_authors.html
{% extends "theme/base.html" %}
{% block content %}
<div class="flex items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Authors</h1>
</div>
<div class="grid justify-center pb-2 p-5">
    {% for author in authors %}
    <a href="{% url 'test_app:specific_author' author.id %}"
       class="font-normal text-gray-700 dark:text-gray-600 hover:text-blue-500">{{ author.fullname }}</a>
    {% endfor %}
</div>
{% include "theme/pagination.html" %}

{% endblock %}

WEB/module_10/backend/test_app/templates/test_app/all_tags.html
{% extends "theme/base.html" %}
{% block content %}
<div class="flex items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Tags</h1>
</div>
<div class="grid justify-center pb-2 p-5">
    {% for tag in tags %}
    <a href="{% url 'test_app:specific_tag'  tagname=tag%}"
       class="font-normal text-gray-700 dark:text-gray-600 hover:text-blue-500">#{{ tag.word }}</a>
    {% endfor %}
</div>
{% include "theme/pagination.html" %}

{% endblock %}

WEB/module_10/backend/test_app/templates/test_app/base.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="test page">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://flowbite.com/docs/flowbite.min.js?v=2.2.1a"></script>
    {% tailwind_css %}
</head>
{% include "test_app/header.html" %}
<body class="bg-slate-300 font-serif leading-normal tracking-normal h-screen">
<div class="container mx-auto font-sans">
    {% block content %}{% endblock %}
{% include "test_app/footer.html" %}
</div>
</body>
</html>

WEB/module_10/backend/test_app/templates/test_app/footer.html
<footer class="font-sans bg-white rounded-lg shadow m-4 dark:bg-gray-800">
    <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
      <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="https://flowbite.com/"
                                                                                      class="hover:underline">Flowbite™</a>. All Rights Reserved.
    </span>
        <ul class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0">
            {% include "test_app/footer_menu.html"%}
        </ul>
    </div>
</footer>

WEB/module_10/backend/test_app/templates/test_app/header.html
<nav class="bg-white w-max-screen border-gray-200 dark:bg-gray-900">
    <div class="font-sans flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="https://flowbite.com/" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo"/>
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Flowbite</span>
        </a>
        <div class="flex items-center md:order-2 space-x-3 md:space-x-10 rtl:space-x-reverse">
            <!-- div for search bar -->
            <div class="relative hidden md:block">
                <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                    <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                    </svg>
                    <span class="sr-only">Search icon</span>
                </div>
                <input type="text" id="search-navbar"
                       class="block w-full p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                       placeholder="Search...">
            </div>


            <button type="button"
                    class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
                    id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown"
                    data-dropdown-placement="bottom">
                <span class="sr-only">Open user menu</span>
                <img class="w-8 h-8 rounded-full" src="https://cdn-icons-png.flaticon.com/512/149/149071.png"
                     alt="user photo">
            </button>
            <!-- Dropdown menu -->
            {% include "test_app/user_menu.html" %}

            <button data-collapse-toggle="navbar-user" type="button"
                    class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                    aria-controls="navbar-user" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                     viewBox="0 0 17 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                          d="M1 1h15M1 7h15M1 13h15"/>
                </svg>
            </button>
        </div>

        <!--mobile version menu-->
        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
            <!-- div for search bar -->
            <div class="relative mt-3 md:hidden">
                <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                    <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                    </svg>
                </div>
                <input type="text" id="search-navbar-mobile"
                       class="block w-full p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                       placeholder="Search...">
            </div>
            <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                {% include "test_app/menu.html"%}
            </ul>
        </div>

    </div>
</nav>

WEB/module_10/backend/test_app/templates/test_app/index.html
{% extends "theme/base.html" %}

{% block content %}
<div class="flex items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Quotes</h1>
</div>

{% include "theme/quote_card.html" %}
{% include "theme/pagination.html" %}



{% endblock %}

WEB/module_10/backend/test_app/templates/test_app/single_author.html
{% extends "theme/base.html" %}
{% block content %}
<div class="flex items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">{{ author.fullname }}</h1>
</div>
<div class="bg-gray-100 dark:text-gray-200 p-4  rounded-md shadow-md dark:bg-gray-800">
    <p class="text-lg font-bold mb-2">
        Author Information
    </p>
    <p class="text-gray-600 dark:text-gray-400 mb-2">
        Born on <span class="font-semibold">{{ author.born_date }}</span> in {{ author.born_location }}
    </p>
    <p class="text-gray-800 dark:text-gray-300">
        {{ author.description }}
    </p>
    <div class="flex flex-wrap basis-1/3 gap-x-2 pl-3 font-normal text-sm text-gray-700 dark:text-gray-600">
                {% load humanize %}
                <p>Added by: {{ author.created_by }} {{ author.date_created|naturaltime }}</p>
                <div class="flex">
                    {% if author.created_by and author.created_by.id == user.id %}
                    <div class="text-blue-600 px-3">
                        <a href="{% url 'users:edit_author' author.id %}" class="#">Edit card</a>
                    </div>
                    <div class="text-red-600 px-3">
                        <a href="{% url 'users:delete_author' author.id %}">Delete card</a>
                    </div>
                    {% endif %}
                </div>
            </div>
</div>

<div class="flex items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Quotes by {{ author.fullname }}:</h1>
</div>
{% include "theme/quote_card.html" %}

{% include "theme/pagination.html" %}

{% endblock %}

WEB/module_10/backend/test_app/templates/test_app/specific_tag.html
{% extends "theme/base.html" %}

{% block content %}
<div class="flex items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">
        {% if request.path|slice:"/tags/" %}
            {% with tagname=request.path|cut:"/tags/"|slice:"/" %}
            #{{ tagname }}
            {% endwith %}
        {% endif %}
    </h1>
</div>
{% include "theme/quote_card.html" %}


{% include "theme/pagination.html "%}

{% endblock %}

WEB/module_10/backend/test_app/templates/test_app/user_menu.html
            <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600"
                 id="user-dropdown">
                <div class="px-4 py-3">
                    <span class="block text-sm text-gray-900 dark:text-white">Bonnie Green</span>
                    <span class="block text-sm  text-gray-500 truncate dark:text-gray-400">name@flowbite.com</span>
                </div>
                <ul class="py-2" aria-labelledby="user-menu-button">
                    <li>
                        <a href="#"
                           class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Login</a>
                    </li>
                    <li>
                        <a href="#"
                           class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Register</a>
                    </li>
                    <li>
                        <a href="#"
                           class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Dashboard</a>
                    </li>
                    <li>
                        <a href="#"
                           class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Settings</a>
                    </li>
                    <li>
                        <a href="#"
                           class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Sign
                            out</a>
                    </li>
                </ul>
            </div>