WEB/module_10/backend/homeworkproj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("test_app.urls")),
    path("admin/", admin.site.urls),
    path("user/", include("users.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

WEB/module_10/backend/test_app/urls.py
from django.urls import path

from . import views

app_name = "test_app"

urlpatterns = [
    path("", views.QuotesListView.as_view(), name="index"),
    path("authors/<pk>", views.AuthorDetailView.as_view(), name="specific_author"),
    path("authors/", views.AuthorsListView.as_view(), name="all_authors"),
    path("tags/", views.TagsListView.as_view(), name="all_tags"),
    path(
        "tags/<str:tagname>", views.QuotesByTagListView.as_view(), name="specific_tag"
    ),
]

WEB/module_10/backend/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.sign_in, name="login"),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("signout/", views.SignOutView.as_view(), name="sign_out"),
    path("add-quote/", views.QuoteCreateView.as_view(), name="add_quote"),
    path("add-author/", views.AuthorCreateView.as_view(), name="add_author"),
    path("add-tag/", views.TagCreateView.as_view(), name="add_tag"),
    path("edit-quote/<pk>", views.QuoteUpdateView.as_view(), name="edit_quote"),
    path("delete-quote/<pk>", views.QuoteDeleteView.as_view(), name="delete_quote"),
    path("edit-author/<pk>", views.AuthorUpdateView.as_view(), name="edit_author"),
    path("delete-author/<pk>", views.AuthorDeleteView.as_view(), name="delete_author"),
    path("edit-tag/<pk>", views.TagUpdateView.as_view(), name="edit_tag"),
    path("delete-tag/<pk>", views.TagDeleteView.as_view(), name="delete_tag"),
]

WEB/module_10/backend/users/models.py
from django.db import models

# Create your models here.

WEB/module_10/backend/users/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm,
                                       UsernameField)
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from test_app.models import Author, Quote, Tag  # noqa

form_style = "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"


class RegisterForm(UserCreationForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={"class": form_style}),
    )
    password1 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(attrs={"class": form_style}),
    )
    password2 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(attrs={"class": form_style}),
    )

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]


class LoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput(attrs={"autofocus": True, "class": form_style})
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "current-password", "class": form_style}
        ),
    )

    class Meta:
        model = User
        fields = ["username", "password"]


form_field_style = "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-600 dark:focus:ring-blue-500 dark:focus:border-blue-500"
form_textfield_style = "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"


class AddQuoteForm(forms.ModelForm):
    author = forms.ModelChoiceField(
        queryset=Author.objects.all(),
        widget=forms.Select(attrs={"class": form_field_style}),
    )
    quote = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={"class": form_textfield_style, "rows": 4})
        # Adjust cols and rows as needed "cols": 80
    )
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.SelectMultiple(attrs={"class": form_field_style}),
    )

    class Meta:
        model = Quote
        fields = ["author", "quote", "tags"]


class AddAuthorForm(forms.ModelForm):
    fullname = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(attrs={"class": form_field_style}),
    )
    born_date = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={"class": form_field_style}),
    )
    born_location = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={"class": form_field_style}),
    )
    description = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={"class": form_textfield_style, "rows": 4}),
    )

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class AddTagForm(forms.ModelForm):
    word = forms.CharField(
        max_length=35,
        required=True,
        widget=forms.TextInput(attrs={"class": form_style}),
    )

    class Meta:
        model = Tag
        fields = ["word"]

WEB/module_10/backend/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DeleteView, ListView, UpdateView,
                                  View)
from test_app.models import Author, Quote, Tag  # noqa

from .forms import (AddAuthorForm, AddQuoteForm, AddTagForm, LoginForm,
                    RegisterForm)


def register(request):
    if request.user.is_authenticated:
        return redirect(to="test_app:index")

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="users:login")
        else:
            return render(request, "users/register.html", context={"form": form})

    return render(request, "users/register.html", context={"form": RegisterForm()})


def sign_in(request):
    if request.user.is_authenticated:
        return redirect(to="test_app:index")
    if request.method == "POST":
        user = authenticate(
            username=request.POST["username"], password=request.POST["password"]
        )
        if user is None:
            messages.error(request, "Username or password didn't match")
            return redirect(to="users:login")
        login(request, user)
        return redirect(to="users:dashboard")
    return render(request, "users/login.html", context={"form": LoginForm()})


# @login_required
@method_decorator(login_required, name="dispatch")
class DashboardView(ListView):
    model = Quote
    template_name = "users/dashboard.html"
    success_url = reverse_lazy("dashboard")
    context_object_name = "quotes"
    paginate_by = 2

    # ordering = ["date_created"]

    def get_queryset(self):
        queryset = super(DashboardView, self).get_queryset()
        return queryset.filter(created_by=self.request.user).order_by("date_created")

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        quotes = Quote.objects.filter(created_by=self.request.user).order_by(
            "-date_created"
        )
        authors = Author.objects.filter(created_by=self.request.user).order_by(
            "-date_created"
        )
        tags = Tag.objects.filter(created_by=self.request.user).order_by(
            "-date_created"
        )
        paginator_quotes = Paginator(quotes, 4)
        # paginator_authors = Paginator(authors, 4)
        context["quotes"] = paginator_quotes
        context["authors"] = authors
        context["tags"] = tags
        return context


@method_decorator(login_required, name="dispatch")
class SignOutView(View):
    def get(self, request):
        logout(request)
        return redirect("test_app:index")


@method_decorator(login_required, name="dispatch")
class QuoteCreateView(CreateView):
    model = Quote
    form_class = AddQuoteForm
    template_name = "users/add_quote.html"
    success_url = reverse_lazy("users:dashboard")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class AuthorCreateView(CreateView):
    model = Author
    form_class = AddAuthorForm
    template_name = "users/add_author.html"
    success_url = reverse_lazy("users:dashboard")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class TagCreateView(CreateView):
    model = Tag
    form_class = AddTagForm
    template_name = "users/add_tag.html"
    success_url = reverse_lazy("users:dashboard")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class QuoteUpdateView(UpdateView):
    model = Quote
    form_class = AddQuoteForm
    template_name = "users/add_quote.html"
    success_url = reverse_lazy("users:dashboard")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.created_by != self.request.user:
            raise Http404("You are not allowed to edit this Quote.")
        return obj


@method_decorator(login_required, name="dispatch")
class QuoteDeleteView(DeleteView):
    model = Quote
    template_name = "users/delete_confirm_quote.html"
    success_url = reverse_lazy("users:dashboard")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.created_by != self.request.user:
            raise Http404("You are not allowed to delete this Quote.")
        return obj


@method_decorator(login_required, name="dispatch")
class AuthorUpdateView(UpdateView):
    model = Author
    form_class = AddAuthorForm
    template_name = "users/add_author.html"
    success_url = reverse_lazy("users:dashboard")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.created_by != self.request.user:
            raise Http404("You are not allowed to edit this Author.")
        return obj


@method_decorator(login_required, name="dispatch")
class AuthorDeleteView(DeleteView):
    model = Author
    template_name = "users/delete_confirm_author.html"
    success_url = reverse_lazy("users:dashboard")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.created_by != self.request.user:
            raise Http404("You are not allowed to delete this Author.")
        return obj


@method_decorator(login_required, name="dispatch")
class TagUpdateView(UpdateView):
    model = Tag
    template_name = "users/add_tag.html"
    success_url = reverse_lazy("users:dashboard")
    form_class = AddTagForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.created_by != self.request.user:
            raise Http404("You are not allowed to edit this Author.")
        return obj


@method_decorator(login_required, name="dispatch")
class TagDeleteView(DeleteView):
    model = Tag
    template_name = "users/delete_confirm_tag.html"
    success_url = reverse_lazy("users:dashboard")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.created_by != self.request.user:
            raise Http404("You are not allowed to delete this Author.")
        return obj

WEB/module_10/backend/users/templates/users/add_author.html
{% extends "theme/base.html" %}

{% block content %}

<div class="flex items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Add Author</h1>

</div>

<form method="post">
{% csrf_token %}
    fullname:
    {{ form.fullname }}
    born_date:
    {{ form.born_date }}
    born_location:
    {{ form.born_location }}
    description:
    {{ form.description }}
    <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Submit
    </button>
</form>


{% endblock %}

WEB/module_10/backend/users/templates/users/add_quote.html
{% extends "theme/base.html" %}

{% block content %}

<div class="flex items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Add Quote</h1>

</div>

<form method="post">
    {% csrf_token %}
    {{ form.author }}
    {{ form.quote }}
    {{ form.tags }}
    <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Submit
    </button>
</form>


{% endblock %}

WEB/module_10/backend/users/templates/users/add_tag.html
{% extends "theme/base.html" %}

{% block content %}

<div class="flex items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Add Author</h1>

</div>

<form method="post">
{% csrf_token %}
    tag:
    {{ form.word }}
    <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Submit
    </button>
</form>


{% endblock %}

WEB/module_10/backend/users/templates/users/dashboard.html
{% extends "theme/base.html" %}

{% block content %}
<p class="">Logged in as: {% if user.is_authenticated %}{{ user.username }}{% endif %}</p>
<div class="grid items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">My quotes:</h1>
    <hr class="m-10">
</div>

{% include "theme/quote_card.html" %}
<!--pagination quotes-->
<div class="flex items-center justify-center pt-10 pb-3">
    <div class="flex">
        <!-- Previous Button -->
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}"
           class="flex items-center justify-center px-4 h-10 me-3 text-base font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
            <svg class="w-3.5 h-3.5 me-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                 fill="none" viewBox="0 0 14 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M13 5H1m0 0 4 4M1 5l4-4"/>
            </svg>
            Previous
        </a>
        {% endif %}
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}"
           class="flex items-center justify-center px-4 h-10 text-base font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
            Next
            <svg class="w-3.5 h-3.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                 fill="none" viewBox="0 0 14 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M1 5h12m0 0L9 1m4 4L9 9"/>
            </svg>
        </a>
        {% endif %}
    </div>
</div>


<!--authors section-->
<div class="grid items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">My Authors:</h1>
    <hr class="m-10">
</div>

<div class="grid justify-center pb-2 p-5">
    {% for author in authors %}
    <a href="{% url 'test_app:specific_author' author.id %}"
       class="font-normal text-gray-700 dark:text-gray-600 hover:text-blue-500">{{ author.fullname }}</a>
    {% endfor %}
</div>


<!--tags section-->
<div class="grid items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">My Tags:</h1>
    <hr class="m-10">
</div>

<div class="grid justify-center pb-2 p-5">
    {% for tag in tags %}
    <div class="flex basis-3/5">
        <a href="{% url 'test_app:specific_tag' tag %}"
           class="font-normal text-gray-700 dark:text-gray-600 hover:text-blue-500">#{{ tag.word }}</a>
        <div class="flex flex-wrap basis-1/3 gap-x-2 pl-3 font-normal text-sm text-gray-700 dark:text-gray-600">
            {% if tag.created_by and tag.created_by.id == user.id %}
            <div class="flex text-blue-600 px-3 basis-1/5">
                <a href="{% url 'users:edit_tag' tag.id %}" class="#">Edit tag</a>
            </div>
            <div class="flex text-red-600 px-3 basis-1/5">
                <a href="{% url 'users:delete_tag' tag.id %}">Delete tag</a>
            </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}

WEB/module_10/backend/users/templates/users/delete_confirm.html
{% extends "theme/base.html" %}

{% block content %}
<p class="">Logged in as: {% if user.is_authenticated %}{{ user.username }}{% endif %}</p>
<div class="grid items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Deleting</h1>
    <hr class="m-10">
</div>

<form method="post" action="{% url 'users:delete_quote' pk=object.pk %}" class="max-w-sm mx-auto">
    {% csrf_token %}
    <div class="mb-5">
        <p class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-700">
            Are you sure you want to delete "{{ object }}"?
        </p>
    </div>
    <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Confirm
    </button>
    <button type="reset" class="text-gray-700 bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-blue-800">
            Reset
        </button>
</form>

{% include "theme/pagination.html" %}
{% endblock %}

WEB/module_10/backend/users/templates/users/delete_confirm_author.html
{% extends "theme/base.html" %}

{% block content %}
<p class="">Logged in as: {% if user.is_authenticated %}{{ user.username }}{% endif %}</p>
<div class="grid items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Deleting</h1>
    <hr class="m-10">
</div>

<form method="post" action="{% url 'users:delete_author' pk=object.pk %}" class="max-w-sm mx-auto">
    {% csrf_token %}
    <div class="mb-5">
        <p class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-700">
            Are you sure you want to delete "{{ object }}"?
        </p>
    </div>
    <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Confirm
    </button>
    <button type="reset" class="text-gray-700 bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-blue-800">
            Reset
        </button>
</form>

{% include "theme/pagination.html" %}
{% endblock %}

WEB/module_10/backend/users/templates/users/delete_confirm_quote.html
{% extends "theme/base.html" %}

{% block content %}
<p class="">Logged in as: {% if user.is_authenticated %}{{ user.username }}{% endif %}</p>
<div class="grid items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Deleting</h1>
    <hr class="m-10">
</div>

<form method="post" action="{% url 'users:delete_quote' pk=object.pk %}" class="max-w-sm mx-auto">
    {% csrf_token %}
    <div class="mb-5">
        <p class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-700">
            Are you sure you want to delete "{{ object }}"?
        </p>
    </div>
    <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Confirm
    </button>
    <button type="reset" class="text-gray-700 bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-blue-800">
            Reset
        </button>
</form>

{% include "theme/pagination.html" %}
{% endblock %}

WEB/module_10/backend/users/templates/users/delete_confirm_tag.html
{% extends "theme/base.html" %}

{% block content %}
<p class="">Logged in as: {% if user.is_authenticated %}{{ user.username }}{% endif %}</p>
<div class="grid items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Deleting</h1>
    <hr class="m-10">
</div>

<form method="post" action="{% url 'users:delete_tag' pk=object.pk %}" class="max-w-sm mx-auto">
    {% csrf_token %}
    <div class="mb-5">
        <p class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-700">
            Are you sure you want to delete "{{ object }}"?
        </p>
    </div>
    <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Confirm
    </button>
    <button type="reset" class="text-gray-700 bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-blue-800">
            Reset
        </button>
</form>

{% include "theme/pagination.html" %}
{% endblock %}

WEB/module_10/backend/users/templates/users/login.html
{% extends "theme/base.html" %}

{% block content %}
<div class="flex items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Login</h1>
</div>
{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
<div class="flex">
    <form action="{% url 'users:login' %}" method="post" class="max-w-sm mx-auto mt-10">
        {% csrf_token %}
        <div class="mb-5">
            <label> Username:
                {{ form.username }}
            </label>
        </div>

        <div class="mb-5">
            <label>Password:
                {{ form.password }}
            </label>
        </div>

        <div class="grid pt-8 items-center space-4">
            <button type="submit" class="m-1 w-15 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 text-white font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit</button>
            <button type="reset" class="m-1 w-15 bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:outline-none focus:ring-gray-300 text-gray-800 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-gray-600 dark:hover:bg-gray-400 dark:focus:ring-gray-600">Reset</button>
        </div>
    </form>
</div>

{% include "theme/pagination.html" %}


{% endblock %}

WEB/module_10/backend/users/templates/users/register.html
{% extends "theme/base.html" %}

{% block content %}
<div class="flex items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Register</h1>
</div>
<div class="flex" >
    <form method="post" action="{% url 'users:register' %}" class="max-w-sm mx-auto mt-10">
        {% csrf_token %}
        <div class="mb-5">
            <label for="id_username" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-900">
                Username:
            </label>
            {{ form.username }}
            <span class="text-red-500 flex items-center space-x-3 rtl:space-x-reverse">{{ form.errors.username }}</span>
        </div>

        <div class="mb-5">
            <label for="id_password1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-900">
                Password:
            </label>
            {{ form.password1 }}
            <span class="text-red-500">{{ form.errors.password1 }}</span>
        </div>

        <div class="mb-5">
            <label for="id_password2" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-900">
                Password confirmation:
            </label>
            {{ form.password2 }}
            <span class="text-red-500">{{ form.errors.password2 }}</span>
        </div>

        <div class="grid pt-8 items-center space-4">
            <button type="submit"
                    class="m-1 w-15 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 text-white font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Submit
            </button>
            <button type="reset"
                    class="m-1 w-15 bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:outline-none focus:ring-gray-300 text-gray-800 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-gray-600 dark:hover:bg-gray-400 dark:focus:ring-gray-600">
                Reset
            </button>
        </div>
    </form>
</div>


{% include "theme/pagination.html" %}


{% endblock %}