WEB/module_10/backend/homeworkproj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("test_app.urls")),
    path("admin/", admin.site.urls),
    path("user/", include("users.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

WEB/module_10/backend/test_app/urls.py
from django.urls import path

from . import views

app_name = "test_app"

urlpatterns = [
    path("", views.QuotesListView.as_view(), name="index"),
    path("authors/<pk>", views.AuthorDetailView.as_view(), name="specific_author"),
    path("authors/", views.AuthorsListView.as_view(), name="all_authors"),
    path("tags/", views.TagsListView.as_view(), name="all_tags"),
    path(
        "tags/<str:tagname>", views.QuotesByTagListView.as_view(), name="specific_tag"
    ),
]

WEB/module_10/backend/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.sign_in, name="login"),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("signout/", views.SignOutView.as_view(), name="sign_out"),
    path("add-quote/", views.QuoteCreateView.as_view(), name="add_quote"),
    path("add-author/", views.AuthorCreateView.as_view(), name="add_author"),
    path("add-tag/", views.TagCreateView.as_view(), name="add_tag"),
    path("edit-quote/<pk>", views.QuoteUpdateView.as_view(), name="edit_quote"),
    path("delete-quote/<pk>", views.QuoteDeleteView.as_view(), name="delete_quote"),
    path("edit-author/<pk>", views.AuthorUpdateView.as_view(), name="edit_author"),
    path("delete-author/<pk>", views.AuthorDeleteView.as_view(), name="delete_author"),
    path("edit-tag/<pk>", views.TagUpdateView.as_view(), name="edit_tag"),
    path("delete-tag/<pk>", views.TagDeleteView.as_view(), name="delete_tag"),
]

WEB/module_10/backend/theme/templates/theme/base.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="test page">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://flowbite.com/docs/flowbite.min.js?v=2.2.1a"></script>
    {% tailwind_css %}
</head>
{% include "theme/header.html" %}
<body class="bg-slate-300 font-serif leading-normal tracking-normal h-screen">
<div class="container mx-auto font-sans">
    {% block content %}{% endblock %}
    {% include "theme/footer.html" %}
</div>
</body>
</html>

WEB/module_10/backend/theme/templates/theme/footer.html
<footer class="font-sans bg-white rounded-lg shadow m-4 dark:bg-gray-800">
    <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
      <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="https://flowbite.com/"
                                                                                      class="hover:underline">Flowbite™</a>. All Rights Reserved.
    </span>
        <ul class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0">
            {% include "theme/footer_menu.html"%}
        </ul>
    </div>
</footer>

WEB/module_10/backend/theme/templates/theme/footer_menu.html
<li>
    <a href="#" class="hover:underline me-4 md:me-6">About</a>
</li>

WEB/module_10/backend/theme/templates/theme/header.html
<nav class="bg-white w-max-screen border-gray-200 dark:bg-gray-900">
    <div class="font-sans flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="https://flowbite.com/" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo"/>
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Flowbite</span>
        </a>
        <div class="flex items-center md:order-2 mr-4 space-x-3 md:space-x-10 rtl:space-x-reverse">
            <!-- div for search bar -->
            <div class="relative hidden md:block">
                <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                    <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                    </svg>
                    <span class="sr-only">Search icon</span>
                </div>
                <input type="text" id="search-navbar"
                       class="block w-full p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                       placeholder="Search...">
            </div>


            <button type="button"
                    class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
                    id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown"
                    data-dropdown-placement="bottom">
                <span class="sr-only">Open user menu</span>
                <img class="w-8 h-8 rounded-full" src="https://cdn-icons-png.flaticon.com/512/149/149071.png"
                     alt="user photo">
            </button>
            <!-- Dropdown menu -->
            {% include "theme/user_menu.html" %}

            <button data-collapse-toggle="navbar-user" type="button"
                    class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                    aria-controls="navbar-user" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                     viewBox="0 0 17 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                          d="M1 1h15M1 7h15M1 13h15"/>
                </svg>
            </button>
        </div>

        <!--mobile version menu-->
        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
            <!-- div for search bar -->
            <div class="relative mt-3 md:hidden">
                <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                    <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                    </svg>
                </div>
                <input type="text" id="search-navbar-mobile"
                       class="block w-full p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                       placeholder="Search...">
            </div>
            <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                {% include "theme/menu.html"%}
            </ul>
        </div>

    </div>
</nav>

WEB/module_10/backend/theme/templates/theme/menu.html
<li>
    <a href="{% url 'test_app:index' %}"
       class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500"
       aria-current="page">Home</a>
</li>
<li>
    <a href="{% url 'test_app:all_authors' %}"
       class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Authors</a>
</li>
<li>
    <a href="{% url 'test_app:all_tags' %}"
       class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Tags</a>
</li>

WEB/module_10/backend/theme/templates/theme/pagination.html
<div class="flex items-center justify-center pt-10 pb-3">
    <div class="flex">
        <!-- Previous Button -->
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}"
           class="flex items-center justify-center px-4 h-10 me-3 text-base font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
            <svg class="w-3.5 h-3.5 me-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                 fill="none" viewBox="0 0 14 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M13 5H1m0 0 4 4M1 5l4-4"/>
            </svg>
            Previous
        </a>
        {% endif %}
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}"
           class="flex items-center justify-center px-4 h-10 text-base font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
            Next
            <svg class="w-3.5 h-3.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                 fill="none" viewBox="0 0 14 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M1 5h12m0 0L9 1m4 4L9 9"/>
            </svg>
        </a>
        {% endif %}
    </div>
</div>

WEB/module_10/backend/theme/templates/theme/quote_card.html
<div class="grid grid-cols-1 gap-4">
    {% for quote in page_obj %}
    <div class="flex items-center mb-5 justify-center">
        <div class="block w-1/2 p-5 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-800 dark:hover:border-gray-200">
            <p class="text-right italic mb-6"><a
                    href="{% url 'test_app:specific_author' quote.author.id %}"
                    class="mb-4 text-lg text-right  tracking-tight text-gray-900 dark:text-white">
                {{quote.author.fullname}}</a></p>
            <div class="flex flex-nowrap px-5">
                <div class="flex pt-1 pr-5">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                         class="w-2 h-2 text-gray-400 mb-8"
                         viewBox="0 0 975.036 975.036">
                        <path d="M925.036 57.197h-304c-27.6 0-50 22.4-50 50v304c0 27.601 22.4 50 50 50h145.5c-1.9 79.601-20.4 143.3-55.4 191.2-27.6 37.8-69.399 69.1-125.3 93.8-25.7 11.3-36.8 41.7-24.8 67.101l36 76c11.6 24.399 40.3 35.1 65.1 24.399 66.2-28.6 122.101-64.8 167.7-108.8 55.601-53.7 93.7-114.3 114.3-181.9 20.601-67.6 30.9-159.8 30.9-276.8v-239c0-27.599-22.401-50-50-50zM106.036 913.497c65.4-28.5 121-64.699 166.9-108.6 56.1-53.7 94.4-114.1 115-181.2 20.6-67.1 30.899-159.6 30.899-277.5v-239c0-27.6-22.399-50-50-50h-304c-27.6 0-50 22.4-50 50v304c0 27.601 22.4 50 50 50h145.5c-1.9 79.601-20.4 143.3-55.4 191.2-27.6 37.8-69.4 69.1-125.3 93.8-25.7 11.3-36.8 41.7-24.8 67.101l35.9 75.8c11.601 24.399 40.501 35.2 65.301 24.399z"></path>
                    </svg>
                </div>
                <div class="flex"><p class="flex font-normal text-gray-700 dark:text-gray-400">
                    {{ quote.quote }}</p></div>
            </div>
            <div class="flex basis-2/3 pb-2 p-5">
                {% for tag in quote.tags.all %}
                <a href="{% url 'test_app:specific_tag' tagname=tag %}"
                   class="font-normal text-gray-700 dark:text-gray-600 hover:text-blue-500">#{{ tag }}</a>
                {% endfor %}
            </div>
            <div class="flex flex-wrap basis-1/3 gap-x-2 pl-3 font-normal text-sm text-gray-700 dark:text-gray-600">
                {% load humanize %}
                <p>Added by: {{ quote.created_by }} {{ quote.date_created|naturaltime }}</p>
                <div class="flex">
                    {% if quote.created_by and quote.created_by.id == user.id %}
                    <div class="text-blue-600 px-3">
                        <a href="{% url 'users:edit_quote' quote.id %}" class="#">Edit card</a>
                    </div>
                    <div class="text-red-600 px-3">
                        <a href="{% url 'users:delete_quote' quote.id %}">Delete card</a>
                    </div>
                    {% endif %}
                </div>
            </div>

        </div>
    </div>
    {% endfor %}
</div>

WEB/module_10/backend/theme/templates/theme/user_menu.html
            <div class="z-50 hidden text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600"
                 id="user-dropdown">
                {% if user.is_authenticated %}
                <div class="px-4 py-3">
                    <span class="block text-sm text-gray-900 dark:text-white">{{ user.username }}</span>
                    <span class="block text-sm  text-gray-500 truncate dark:text-gray-400">{{ user.username }}@mail.com</span>
                </div>
                    {% endif %}

                <ul class="py-2" aria-labelledby="user-menu-button">
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'users:dashboard' %}"
                           class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Dashboard</a>
                    </li>
                    <li>
                        <a href="{% url 'users:add_quote' %}"
                           class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Add Quote</a>
                    </li>
                    <li>
                        <a href="{% url 'users:add_author' %}"
                           class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Add Author</a>
                    </li>
                    <li>
                        <a href="{% url 'users:add_tag' %}"
                           class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Add Tag</a>
                    </li>
                    <li>
                        <a href="{% url 'users:sign_out' %}"
                           class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Sign
                            out</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'users:login' %}"
                           class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'users:register' %}"
                           class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>